version: '2'

services:
  php:
    build: ./docker/php
    volumes:
       - ./website:/var/www/html/
#       - /var/log/apache2/blog:var/log/apache2/
    ports:
      - '8000:80'
    environment:
      - production
    depends_on:
      - db
  db:
    build: ./docker/db
  
